# Generated by Django 5.2.7 on 2025-12-01 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_range', models.CharField(choices=[('0-100', '₹0 - ₹100'), ('101-500', '₹101 - ₹500'), ('501-1000', '₹501 - ₹1,000'), ('1001-5000', '₹1,001 - ₹5,000'), ('5001-10000', '₹5,001 - ₹10,000')], max_length=20, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=50, unique=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('operator_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('landline', 'Landline')], max_length=20)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('circle', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('flat_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['operator_name'],
                'indexes': [models.Index(fields=['operator_type', 'is_active'], name='recharge_op_operato_7b9056_idx'), models.Index(fields=['circle'], name='recharge_op_circle_87b6e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100, unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(blank=True, max_length=100, null=True)),
                ('data_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('talktime', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_type', models.CharField(choices=[('data', 'Data Plan'), ('combo', 'Combo Plan'), ('voice', 'Voice Plan'), ('topup', 'Top-up'), ('special', 'Special Recharge'), ('dth', 'DTH Plan')], default='combo', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('eko_plan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_plan_category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='recharge.operator')),
            ],
            options={
                'ordering': ['amount'],
                'indexes': [models.Index(fields=['operator', 'is_active'], name='recharge_pl_operato_156b1a_idx'), models.Index(fields=['amount', 'is_active'], name='recharge_pl_amount_6927f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RechargeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('operator_id', models.CharField(max_length=50)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('landline', 'Landline')], default='prepaid', max_length=20)),
                ('circle', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('consumer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_ref_id', models.CharField(max_length=100)),
                ('eko_transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_message', models.TextField(blank=True, null=True)),
                ('eko_txstatus_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('eko_response_status', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='initiated', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('api_request', models.JSONField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('is_plan_recharge', models.BooleanField(default=False)),
                ('plan_details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='recharge_re_transac_1d0c3c_idx'), models.Index(fields=['user', 'initiated_at'], name='recharge_re_user_id_9ed856_idx'), models.Index(fields=['mobile_number'], name='recharge_re_mobile__4430fa_idx'), models.Index(fields=['status', 'initiated_at'], name='recharge_re_status_c4887d_idx'), models.Index(fields=['payment_status'], name='recharge_re_payment_313129_idx')],
            },
        ),
    ]
