# Generated by Django 5.2.7 on 2025-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operator_type',
            field=models.CharField(choices=[('prepaid', 'Mobile Prepaid'), ('postpaid', 'Mobile Postpaid'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('landline', 'Landline'), ('tax', 'Tax'), ('credit', 'Credit Card'), ('society', 'Housing Society'), ('ott', 'OTT Subscription'), ('education', 'Education Fees'), ('municipal_tax', 'Municipal Tax'), ('clubs', 'Clubs & Associations'), ('cable', 'Cable TV'), ('lpg', 'LPG Cylinder'), ('hospital', 'Hospital'), ('insurance', 'Insurance'), ('loan', 'Loan EMI'), ('fastag', 'FASTag'), ('municipal_services', 'Municipal Services'), ('subscription_2', 'Subscription 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rechargetransaction',
            name='operator_type',
            field=models.CharField(choices=[('prepaid', 'Mobile Prepaid'), ('postpaid', 'Mobile Postpaid'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('landline', 'Landline'), ('tax', 'Tax'), ('credit', 'Credit Card'), ('society', 'Housing Society'), ('ott', 'OTT Subscription'), ('education', 'Education Fees'), ('municipal_tax', 'Municipal Tax'), ('clubs', 'Clubs & Associations'), ('cable', 'Cable TV'), ('lpg', 'LPG Cylinder'), ('hospital', 'Hospital'), ('insurance', 'Insurance'), ('loan', 'Loan EMI'), ('fastag', 'FASTag'), ('municipal_services', 'Municipal Services'), ('subscription_2', 'Subscription 2')], default='prepaid', max_length=20),
        ),
    ]
