# Generated by Django 5.2.7 on 2026-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pan_number', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('employment_status', models.CharField(choices=[('salaried', 'Salaried'), ('self-employed', 'Self Employed')], max_length=20)),
                ('employer_name', models.CharField(max_length=255)),
                ('office_pin_code', models.CharField(max_length=6)),
                ('monthly_income', models.IntegerField()),
                ('external_lead_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
