# Generated by Django 5.2.7 on 2026-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditlinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='creditlinktransaction',
            name='creditlinks_transac_0f9d63_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditlinktransaction',
            name='creditlinks_user_id_575a1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditlinktransaction',
            name='creditlinks_status_1628b7_idx',
        ),
        migrations.RemoveField(
            model_name='creditlinktransaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='creditlinktransaction',
            name='response_status_id',
        ),
        migrations.RemoveField(
            model_name='creditlinktransaction',
            name='response_type_id',
        ),
        migrations.AddField(
            model_name='creditlinktransaction',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditlinktransaction',
            name='customer_mobile',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditlinktransaction',
            name='customer_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditlinktransaction',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creditlinktransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
