# Generated by Django 5.2.7 on 2026-02-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditlinks', '0002_remove_creditlinktransaction_creditlinks_transac_0f9d63_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlinktransaction',
            name='bank_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditlinktransaction',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
