# Generated by Django 5.2.7 on 2026-02-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditlinks', '0003_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalLoan',
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
    ]
