# Generated by Django 5.2.7 on 2026-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditlinks', '0004_delete_personalloan_alter_loan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='lead_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
