# Generated by Django 5.2.7 on 2026-02-02 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSBiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller_id', models.CharField(max_length=20, unique=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('biller_type', models.CharField(choices=[('agent', 'Agent'), ('customer', 'Customer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='CMSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ref_id', models.CharField(max_length=100, unique=True)),
                ('tid', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('redirected', 'Redirected'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('debit_hook_payload', models.JSONField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cms.cmsbiller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
