# Generated by Django 5.2.7 on 2026-01-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_helpdeskticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskticket',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
