# Generated by Django 5.2.7 on 2026-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_helpdeskticket_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskticket',
            name='attachment',
            field=models.CharField(blank=True, help_text='Image URL generated from upload API', max_length=500, null=True),
        ),
    ]
