# Generated by Django 5.2.7 on 2025-11-04 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
        ('services', '0013_servicecategory_require_browse_plan_and_more'),
        ('users', '0016_alter_user_aadhar_card_alter_user_other_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecommission',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='servicecommission',
            name='min_amount',
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['role', 'created_at'], name='commission__role_8264cd_idx'),
        ),
    ]
