# Generated by Django 5.2.7 on 2025-11-25 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0016_roleservicepermission_userservicepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EkoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eko_service_code', models.CharField(max_length=20)),
                ('eko_service_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('service_subcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EkoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('eko_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_ref_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eko_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eko_integration.ekoservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EkoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eko_user_code', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eko_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
