# Generated by Django 5.2.7 on 2025-11-26 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eko_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ekoservice',
            old_name='eko_service_name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='ekoservice',
            name='eko_service_code',
        ),
        migrations.RemoveField(
            model_name='ekoservice',
            name='service_subcategory',
        ),
        migrations.RemoveField(
            model_name='ekotransaction',
            name='eko_service',
        ),
        migrations.AddField(
            model_name='ekoservice',
            name='service_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ekoservice',
            name='service_type',
            field=models.CharField(choices=[('dmt', 'Money Transfer'), ('recharge', 'Mobile Recharge'), ('bbps', 'BBPS Bill Payment')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ekotransaction',
            name='transaction_type',
            field=models.CharField(choices=[('onboard', 'User Onboarding'), ('dmt', 'Money Transfer'), ('recharge', 'Mobile Recharge'), ('bbps', 'BBPS Payment'), ('balance_check', 'Balance Check')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ekotransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='EkoRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('recipient_mobile', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eko_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'account_number', 'ifsc_code')},
            },
        ),
    ]
