# Generated by Django 5.2.7 on 2025-11-26 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMTServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=10)),
                ('charge_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['amount_from'],
            },
        ),
        migrations.CreateModel(
            name='DMTRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_id', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'account_number', 'ifsc_code')},
            },
        ),
        migrations.CreateModel(
            name='DMTTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('eko_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_ref_id', models.CharField(max_length=100, unique=True)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_id', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_mobile', models.CharField(max_length=15)),
                ('recipient_account', models.CharField(max_length=50)),
                ('recipient_ifsc', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('channel', models.CharField(choices=[('imps', 'IMPS'), ('neft', 'NEFT')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('hold', 'Hold')], default='initiated', max_length=20)),
                ('eko_status', models.IntegerField(blank=True, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=100, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('latlong', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmt_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['reference_number'], name='dmt_dmttran_referen_8fb359_idx'), models.Index(fields=['customer_mobile'], name='dmt_dmttran_custome_951663_idx'), models.Index(fields=['status', 'initiated_at'], name='dmt_dmttran_status_d978f3_idx'), models.Index(fields=['eko_transaction_id'], name='dmt_dmttran_eko_tra_e7fe9a_idx')],
            },
        ),
    ]
