# Generated by Django 5.2.7 on 2026-02-14 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_refundrequest_admin_note_refundrequest_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='admin_logos/')),
                ('fevicon_icon', models.ImageField(blank=True, null=True, upload_to='admin_favicon/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='admin_main/')),
                ('project_name', models.CharField(default='My Project', max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_color', models.CharField(default='#1E3A8A', max_length=20)),
                ('secondary_color', models.CharField(default='#10B981', max_length=20)),
                ('theme_color', models.CharField(default='#1E3A8A', max_length=20)),
                ('sidebar_color', models.CharField(default='#10B981', max_length=20)),
                ('navbar_color', models.CharField(default='#10B981', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('font_size', models.CharField(default='14px', max_length=20)),
                ('admin', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
