# Generated by Django 5.2.7 on 2026-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_adminbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbranding',
            name='fevicon_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminbranding',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminbranding',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
