# Generated by Django 5.2.7 on 2026-02-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_adminbranding_fevicon_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
