# Generated by Django 5.2.7 on 2026-02-15 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_custom_domain_user_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_downlines', to=settings.AUTH_USER_MODEL),
        ),
    ]
