# Generated by Django 5.2.7 on 2026-01-09 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='services.serviceform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsubmissionfile',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='services.servicesubmission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleservicepermission',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleservicepermission',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='roleservicepermission',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceform',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceform',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_forms', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_forms', to='services.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.servicecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesubmission',
            name='service_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.serviceform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesubmission',
            name='service_subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userservicepermission',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_user_permissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userservicepermission',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='userservicepermission',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory'),
        ),
        migrations.AddField(
            model_name='userservicepermission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field_id')},
        ),
        migrations.AlterUniqueTogether(
            name='roleservicepermission',
            unique_together={('role', 'service_category'), ('role', 'service_subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='userservicepermission',
            unique_together={('user', 'service_category'), ('user', 'service_subcategory')},
        ),
        migrations.AddIndex(
            model_name='servicesubmission',
            index=models.Index(fields=['submission_id'], name='services_se_submiss_18f339_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubmission',
            index=models.Index(fields=['status'], name='services_se_status_d2c86d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubmission',
            index=models.Index(fields=['submitted_by', 'created_at'], name='services_se_submitt_337dfa_idx'),
        ),
    ]
